### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by flower-kyo** [jinyyy666/CUDA-LSM#2]

**Comment by jinyyy666** [comment]
What are the errors you getting now?

**Comment by flower-kyo** [comment]
Thank you for your kind cooperation. I found the cause of the error and I can run this code now.
 I read your paper “hybrid-macromicro-level-backpropagation-for-training-deep-spiking-neural-networks“.
 Now I have a new trouble. I'm trying to use your code to train a model with EEG data, whose channel number is 3 and length is 3000. First I changed some settings in the configuration file. I set input layer NUM_NEURONS = 3, set output layer NUM_CLASSES = 6, NUM_NEURONS = 6; Modify the weight file according to the number of neurons.
I modify these two files:
![image](https://user-images.githubusercontent.com/33209008/59926140-3a7a8e80-946c-11e9-882f-2114af5d9be5.png)

And set END_TIME =  3000. 
My data file is like this：
Train data folder:
![image](https://user-images.githubusercontent.com/33209008/59925062-d22aad80-9469-11e9-9e3d-d652a90ff93a.png)
3-channel dat file:
![image](https://user-images.githubusercontent.com/33209008/59925239-3483ae00-946a-11e9-8428-608b6f8febeb.png)
I set TEST_EPOCH = 1000 and start trianing. However, after training for hours, I didn't work well.
This is the log file:
![image](https://user-images.githubusercontent.com/33209008/59925611-0ce11580-946b-11e9-8e39-f73e62e5f9ca.png)
I want to ask if I need to modify the parameters of the BSA algorithm, What is wrong with my operation?
Or do  I need to preprocess the EEG data？Looking forward your advice!
Thank you again for your patience and cooperation!

**Comment by jinyyy666** [comment]
1) First of all, you probably do not want to modify those weight files as they are just the internal outputs of the program. 

If you want to let the model reads the weights, you need to config that in the config file like this: https://github.com/jinyyy666/mm-bp-snn/blob/master/Config/SpikingMnistConfig_test.txt

2) It seems that you are using the LSM architecture (judging by the "reservoir")? Is there any reason why you start with this algorithm?

3) The end time is probably too long. Do you think you can condense them by combining four time stamps into one?

4) The number of output firing count is not right. Why are there 10 firing counts? Are you sure that you have changed the config? And are you sure that you are selecting the correct dataset?
