### ISSUE TITLE
The given path: ../2312_600_stable/train does not exist!

### ISSUE THREAD

**Issue by AliLotfi92** [jinyyy666/CUDA-LSM#3]
Hi authors, 

I got this error for MNIST. And different types of error for other dataset as well.

ali@ali-MS-7A69:~/mm-bp-snn$ ./build/CUDA-SNN 6 1
1. MNIST
2. CIFAR-10
3. CHINESE
4. CIFAR-100
5. VOTE MNIST
6. NMnist
7. Spiking Mnist
8. Spoken English Letter
Choose the dataSet to run:

*******************CONFIG*******************
Is Gradient Checking : 0
Allow Dynamic Threshold : 0
Has Boost Weight Train: 1
Use Effect Ratio      : 1
Use Optimizer         : adam
lambda                : 10.000000
beta                  : 0.010000
weight limit          : 8.000000
batch Size            : 1
channels              : 1
Warning::No key word: CROP found in the configuration file
crop                  : -1
Warning::No key word: SCALE found in the configuration file
scale                 : 0.000000
Warning::No key word: ROTATION found in the configuration file
rotation              : 0.000000
Warning::No key word: DISTORTION found in the configuration file
distortion            : 0.000000
imageShow             : 0
Warning::No key word: HORIZONTAL found in the configuration file
HORIZONTAL            : 0
Test_Epoch            : 200
White Noise           : 0.000000
Spike end time        : 540
Warning::No key word: TRAIN_SAMPLES found in the configuration file
Warning::No key word: TEST_SAMPLES found in the configuration file
Train data path       : ../2312_600_stable/train
Test data path        : ../2312_600_stable/test
Train samples         : -1
Test samples          : -1
Train samples per class : -1
Test samples per class  : -1

********data spiking Layer********
NAME          : data
INPUT_NEURONS : 2312
Warning::No key word: NUM_CLASSES found in the configuration file
Warning::No key word: UNDESIRED_LEVEL found in the configuration file
Warning::No key word: DESIRED_LEVEL found in the configuration file
Warning::No key word: MARGIN found in the configuration file
Warning::No key word: ADD_BIAS found in the configuration file

********SPIKING Layer********
NAME               : hidden_0
NUM_NEURONS        : 800
INPUT              : data
VTH                : 15.000000
T_REFRAC           : 2
TAU_M              : 64.000000
TAU_S              : 8.000000
initW              : 1.000000
weightConnect      : 0
initType           : Bernoulli
weightPath         : NULL
lweightPath        : NULL
laterialType       : NULL
reservoirDim       : NULL
localInbStrength   : 0.000000
UNDESIRED_LEVEL    : 0.000000
DESIRED_LEVEL      : 0.000000
MARGIN             : 0.000000
refWeightPath      : NULL
refLWeightPath     : NULL
refOuputTrainPath  : NULL
refOutputTestPath  : NULL
ADD_BIAS           : 0
BIAS_FREQ          : 100000
Warning::No key word: ADD_BIAS found in the configuration file

********SPIKING Layer********
NAME               : output
NUM_NEURONS        : 10
INPUT              : hidden_0
VTH                : 15.000000
T_REFRAC           : 2
TAU_M              : 64.000000
TAU_S              : 8.000000
initW              : 1.000000
weightConnect      : 0
initType           : Bernoulli
weightPath         : NULL
lweightPath        : NULL
laterialType       : LOCAL_INHIBITION
reservoirDim       : NULL
localInbStrength   : 1.000000
UNDESIRED_LEVEL    : 5.000000
DESIRED_LEVEL      : 35.000000
MARGIN             : 5.000000
refWeightPath      : NULL
refLWeightPath     : NULL
refOuputTrainPath  : NULL
refOutputTestPath  : NULL
ADD_BIAS           : 0
BIAS_FREQ          : 100000

The given path: ../2312_600_stable/train does not exist!

**Comment by AliLotfi92** [comment]
for NMINST


ali@ali-MS-7A69:~/mm-bp-snn$ ./build/CUDA-SNN 7 1
1. MNIST
2. CIFAR-10
3. CHINESE
4. CIFAR-100
5. VOTE MNIST
6. NMnist
7. Spiking Mnist
8. Spoken English Letter
Choose the dataSet to run:

*******************CONFIG*******************
Is Gradient Checking : 0
Warning::No key word: DYNAMIC_THRESHOLD found in the configuration file
Allow Dynamic Threshold : 0
Has Boost Weight Train: 1
Use Effect Ratio      : 1
Use Optimizer         : adam
lambda                : 10.000000
beta                  : 0.040000
weight limit          : 8.000000
batch Size            : 1
channels              : 1
Warning::No key word: CROP found in the configuration file
crop                  : -1
Warning::No key word: SCALE found in the configuration file
scale                 : 0.000000
Warning::No key word: ROTATION found in the configuration file
rotation              : 0.000000
Warning::No key word: DISTORTION found in the configuration file
distortion            : 0.000000
imageShow             : 0
Warning::No key word: HORIZONTAL found in the configuration file
HORIZONTAL            : 0
Test_Epoch            : 200
White Noise           : 0.000000
Spike end time        : 400
Warning::No key word: TRAIN_PER_CLASS found in the configuration file
Warning::No key word: TEST_PER_CLASS found in the configuration file
Train data path       : NULL
Test data path        : NULL
Train samples         : 60000
Test samples          : 10000
Train samples per class : -1
Test samples per class  : -1


********data spiking Layer********
NAME          : data
INPUT_NEURONS : 784
Warning::No key word: NUM_CLASSES found in the configuration file
Warning::No key word: UNDESIRED_LEVEL found in the configuration file
Warning::No key word: DESIRED_LEVEL found in the configuration file
Warning::No key word: MARGIN found in the configuration file
Warning::No key word: ADD_BIAS found in the configuration file


********SPIKING Layer********
NAME               : hidden_0
NUM_NEURONS        : 800
INPUT              : data
VTH                : 20.000000
T_REFRAC           : 2
TAU_M              : 64.000000
TAU_S              : 8.000000
initW              : 1.000000
weightConnect      : 0
initType           : Bernoulli
weightPath         : NULL
lweightPath        : NULL
laterialType       : NULL
reservoirDim       : NULL
localInbStrength   : 0.000000
UNDESIRED_LEVEL    : 0.000000
DESIRED_LEVEL      : 0.000000
MARGIN             : 0.000000
refWeightPath      : NULL
refLWeightPath     : NULL
refOuputTrainPath  : NULL
refOutputTestPath  : NULL
ADD_BIAS           : 0
BIAS_FREQ          : 100000
Warning::No key word: ADD_BIAS found in the configuration file


********SPIKING Layer********
NAME               : output
NUM_NEURONS        : 10
INPUT              : hidden_0
VTH                : 8.000000
T_REFRAC           : 2
TAU_M              : 64.000000
TAU_S              : 8.000000
initW              : 1.000000
weightConnect      : 0
initType           : Bernoulli
weightPath         : NULL
lweightPath        : NULL
laterialType       : LOCAL_INHIBITION
reservoirDim       : NULL
localInbStrength   : 1.000000
UNDESIRED_LEVEL    : 5.000000
DESIRED_LEVEL      : 35.000000
MARGIN             : 5.000000
refWeightPath      : NULL
refLWeightPath     : NULL
refOuputTrainPath  : NULL
refOutputTestPath  : NULL
ADD_BIAS           : 0
BIAS_FREQ          : 100000



Cannot open the file: mnist/train-images-idx3-ubyte
CUDA-SNN: /home/ali/mm-bp-snn/readData/readMnistData.cpp:174: void readMnistImg(const string&, std::vector<cuMatrix<float>*, std::allocator<cuMatrix<float>*> >&, int): Assertion `0' failed.
Aborted (core dumped)

**Comment by jinyyy666** [comment]
For the first error: make sure that you have the training path correct.
For the second error: You need to download the MNIST dataset first. Go to the mnist/ and run the script.

**Comment by jinyyy666** [comment]
For the first error, you need to generate the nmnist data. Please go to the nmnist/ folder and run the matlab code here.

**Comment by AliLotfi92** [comment]
Thanks a lot. It worked, I forgot to close this issue.
