### ISSUE TITLE
数据预处理请教

### ISSUE THREAD

**Issue by flower-kyo** [jinyyy666/CUDA-LSM#4]
我要处理的是脑电数据，它只有4个通道，而每个通道的数据长度长达6000。而您的实验中的数据，比如说speech的数据，它有78个通道，而每个通道的数据长度只有1000。
![image](https://user-images.githubusercontent.com/33209008/60391186-1299c380-9b1b-11e9-85e9-e10bab145bd1.png)
跟您的数据相比，我的数据通道数太少而长度太长。
请问这个通道的数量和数据的长度对模型的训练影响大吗？

**Comment by jinyyy666** [comment]
是有影响的 我建议你可以把时间condense一下 比如说把六个点合成一个点 如果六个点中有spike就是1 没有的话就是0

**Comment by jinyyy666** [comment]
而且通道数目太少的话确实会有问题的 建议多一些channel 可以把其他channels进行一下mix来增加 但是会introduce dependency 效果是否会好也不好说
