### ISSUE TITLE
请问能提供论文中提到的测试语音数据集的代码

### ISSUE THREAD

**Issue by lslynf** [jinyyy666/CUDA-LSM#6]

**Comment by jinyyy666** [comment]
这个是TI46的corpus，可以从dropbox这个链接下载： https://www.dropbox.com/s/x45oc90ibmska2k/TI-46.rar?dl=0

**Comment by Roger2148** [comment]
> 这个是TI46的corpus，可以从dropbox这个链接下载： https://www.dropbox.com/s/x45oc90ibmska2k/TI-46.rar?dl=0

TONS OF THANKS
