### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Originofamonia** [jinyyy666/CUDA-LSM#8]
Hi,

I was trying to reproduce your code on ubuntu. I got a make error in the last step: `make -j`.
The error is this:
![image](https://user-images.githubusercontent.com/20205969/96945326-746a0380-14ab-11eb-95db-c305647abb8d.png)
`/CUDA-SNN_generated_ConvSpiking.cu.o' failed
make[2]: *** [CMakeFiles/CUDA-SNN.dir/layers/CUDA-SNN_generated_ConvSpiking.cu.o] Error 1
In file included from /home/edward/PycharmProjects/mm-bp-snn/layers/LayerBase.h:4:0,
                 from /home/edward/PycharmProjects/mm-bp-snn/layers/CombineLayer.h:7,
                 from /home/edward/PycharmProjects/mm-bp-snn/layers/CombineLayer.cu:1:
/home/edward/PycharmProjects/mm-bp-snn/layers/../common/cuMatrix.h:11:10: fatal error: helper_cuda.h: No such file or directory
 #include "helper_cuda.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
CMake Error at CUDA-SNN_generated_CombineLayer.cu.o.cmake:220 (message):
  Error generating
  /home/edward/PycharmProjects/mm-bp-snn/build/CMakeFiles/CUDA-SNN.dir/layers/./CUDA-SNN_generated_CombineLayer.cu.o

CMakeFiles/CUDA-SNN.dir/build.make:274: recipe for target 'CMakeFiles/CUDA-SNN.dir/layers/CUDA-SNN_generated_CombineLayer.cu.o' failed
make[2]: *** [CMakeFiles/CUDA-SNN.dir/layers/CUDA-SNN_generated_CombineLayer.cu.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/CUDA-SNN.dir/all' failed
make[1]: *** [CMakeFiles/CUDA-SNN.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2`

I checked the `helper_cuda.h` file. It's in dir `usr/local/cuda-10.2/samples/common/inc`. So how to fix this error?

Thanks!

**Comment by Originofamonia** [comment]
I encountered the same problem under the Windows environment. 
![image](https://user-images.githubusercontent.com/20205969/96951410-71c2da80-14ba-11eb-9ebd-59bb03c52d6e.png)
I have set the CUDA_SDK_ROOT_DIR correctly, but the project still can't link the `helper_cuda.h` file.

**Comment by jinyyy666** [comment]
It seems like an env variable issue. Have you ever tried to set `CUDA_SDK_ROOT_DIR` correctly in your environment? 

I never encountered this when I first wrote the code around 2018 with Cuda 8. Now you have Cuda 10, and I would expect you to run into some setup issues.

**Comment by jinyyy666** [comment]
And for window, can you please check your PATH variable? What is your PATH variable?

**Comment by jinyyy666** [comment]
For linux, can you please try to add those two paths to your PATH variable: `/usr/local/cuda/samples/common/inc/ (For include file "helper_cuda"); /usr/local/include/opencv/ (Depend on situation)`

Please ignore the content within the `()`

**Comment by jinyyy666** [comment]
And `LD_LIBRARY_PATH` I am not sure which one is being read.

**Comment by Originofamonia** [comment]
Thanks for your reply. In windows, the related environment variables are:
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;
C:\Program Files\opencv\build\x64\vc15
C:\Program Files\CMake\bin
`
I found the `helper_cuda.h` file is in another dir: `C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1\common\inc`. So I added this command in cmake: `include_directories ("${CUDA_INCLUDE_DIRS}/../../../../../ProgramData/NVIDIA Corporation/CUDA Samples/common/inc")`, but the problem is still the same.

Can I also ask how is variable `CUDA_INCLUDE_DIRS` assigned in cmake? Why it has different variable names from the cmake.json file?

Below are my CMakeLists.txt and CMakeSettings.json contents:
![image](https://user-images.githubusercontent.com/20205969/96956562-71c8d780-14c6-11eb-8bbb-bcfe9e477bdd.png)

![image](https://user-images.githubusercontent.com/20205969/96956572-7bead600-14c6-11eb-8956-05ce70a7aa10.png)


Thanks!

**Comment by jinyyy666** [comment]
Can you please add `C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1\common\inc` to your window PATH variable and reload your IDE and retry?

**Comment by Originofamonia** [comment]
Hi Jimmy,

I added `C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1\common\inc` to the `Path` variable. But the problem is still the same. This result is from ctrl+s.
![image](https://user-images.githubusercontent.com/20205969/96958771-62e52380-14cc-11eb-9485-b9a9fa0f2139.png)

It seems the problem is the C++ compiler doesn't know where to find the `helper_cuda.h` file. So are there some methods like adding a path to the python interpreter, so that the C++ compiler knows where to find the library? Because in Visual studio, this folder doesn't have a solution, I can't open the property to set the Additional Include Directories [.](https://stackoverflow.com/questions/4445418/how-to-add-additional-libraries-to-visual-studio-project)

If I use right-click of cmakelists.txt and then build, it has even more errors. So what's the correct way to compile and run this repo in visual studio?

![image](https://user-images.githubusercontent.com/20205969/96959559-54980700-14ce-11eb-8bc2-76be3053b616.png)




Another question is if the cmake step passed, what's the main entry to run this project in visual studio?

Thanks!

**Comment by Originofamonia** [comment]
In ubuntu, I also tried to add `/usr/local/cuda-10.2/samples/common/inc` to either PATH or LD_LIBRARY_PATH, but both ended up failed the `cmake ..`. The error is like this:
![image](https://user-images.githubusercontent.com/20205969/97016314-964e9f00-151a-11eb-8936-05052d0dc611.png)

Another problem is I tried to print out the `MESSAGE("${OPENCV_INCLUDE_DIR}")`, but found a blank line like above.

![image](https://user-images.githubusercontent.com/20205969/97016521-d746b380-151a-11eb-84b8-412689ee2d36.png)
I have tried to add `/usr/local/lib` to either PATH or LD_LIBRARY_PATH. In both cases, cmake can't print the opencv path.

Any ideas on how to solve these?

Thanks!

**Comment by jinyyy666** [comment]
For linux, I think this will be helpful: https://stackoverflow.com/questions/19352941/trying-to-get-cuda-working-sample-cant-find-helper-cuda-h

Just to make sure, where do you add the `/usr/local/lib` to `PATH` var? Is that done in .bashrc/.bash_profile? 

And once you added it, do you try to open a new terminal (that way the new evn vars will be picked up), and try to make clean and rebuild?

For your question: MESSAGE("${OPENCV_INCLUDE_DIR}") is empty because you never set this env var... You probably want to set it in ~/.bash_profile or ~/.bashrc.

**Comment by jinyyy666** [comment]
For setting up the PATH variable, you need to do: 

`export PATH=$PATH:/usr/local/cuda-10.2/samples/common/inc`

**Comment by jinyyy666** [comment]
> Can I also ask how is variable CUDA_INCLUDE_DIRS assigned in cmake? Why it has different variable names from the cmake.json file?

I guess that is being picked up from env?

**Comment by jinyyy666** [comment]
> I found the helper_cuda.h file is in another dir: C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1\common\inc.

After you added this, do you try to re-open the IDE or even restart so that the PATH can be picked up by vscode?

**Comment by jinyyy666** [comment]
Let's focus on fixing your linux build first.

**Comment by kadirkun** [comment]
In the Linux environment, I changed the `include_directories ("${CUDA_INCLUDE_DIRS}/../samples/common/inc")` to `include_directories ("/opt/cuda/samples/common/inc")` in the  `mm-bp-snn/CMakeLists.txt`. And now running perfecly in my system.
Previously, I had got the same `helper_cuda.h` error.

**Comment by jinyyy666** [comment]
@Originofamonia Will @kadirkun 's fix help you? Please let me know. I think the issue is that the include cannot be found correctly.

**Comment by Originofamonia** [comment]
Hi,

Sorry I was busy with other school work these days. You can close this issue, because I don’t have time to work on it recently. Thanks for your help.
